/**
 * Build a local preview page of the whole canon in every style + hero prompts.
 *   node scripts/preview.ts   then open out/preview.html
 */

import { writeFileSync, mkdirSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

import { CANON, asValid, renderDiorama, RENDER_STYLES, animePrompt, generate } from "../src/index.ts";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const out = join(root, "out");
mkdirSync(out, { recursive: true });

const esc = (s: string) => s.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");

const dilemmas = [...CANON, asValid(generate(42)), asValid(generate(777))];

const sections = dilemmas
  .map((raw) => {
    const d = asValid(raw);
    const cells = RENDER_STYLES.map(
      (style) => `<figure class="cell"><figcaption>${style}</figcaption>${renderDiorama(d, { style })}</figure>`,
    ).join("");
    return `<section><h2>${esc(d.title)} <span class="id">${d.id} · ${d.domain ?? d.hazard.kind}</span></h2>
<div class="grid">${cells}</div>
<details><summary>anime hero prompt (NijiJourney 6)</summary><pre>${esc(animePrompt(d).niji)}</pre></details></section>`;
  })
  .join("\n");

const html = `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Switchyard — preview</title>
<style>
:root{color-scheme:light}
body{font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;background:#efece4;color:#2a2a28;margin:0;padding:28px;max-width:1100px;margin-inline:auto}
h1{font-weight:600;font-size:26px;margin:0 0 4px}
.sub{color:#777;margin:0 0 28px}
h2{font-weight:500;font-size:18px;margin:34px 0 10px;border-bottom:1px solid #d8d3c7;padding-bottom:6px}
.id{font:12px/1 monospace;color:#9a948a;font-weight:400}
.grid{display:grid;grid-template-columns:1fr 1fr;gap:16px}
.cell{margin:0;background:#fff;border:1px solid #e2ddd2;border-radius:12px;padding:10px;overflow:hidden}
.cell figcaption{font:600 11px/1 monospace;color:#9a948a;letter-spacing:.04em;text-transform:uppercase;margin-bottom:8px}
.cell svg{width:100%;height:auto;display:block;border-radius:6px}
details{margin:10px 0 0}summary{cursor:pointer;color:#7a756b;font:13px/1 monospace}
pre{white-space:pre-wrap;font:12px/1.6 monospace;color:#555;background:#faf8f3;border:1px solid #eee5d6;border-radius:8px;padding:12px;margin:8px 0 0}
footer{margin:48px 0 12px;color:#9a948a;font:13px/1.5 monospace}
@media(max-width:680px){.grid{grid-template-columns:1fr}}
</style></head><body>
<h1>Switchyard</h1>
<p class="sub">the whole canon, every style — generated by the engine. open me in a browser; the animated style loops.</p>
${sections}
<footer>node examples/demo.ts · node scripts/gallery.ts · ${dilemmas.length} dilemmas × ${RENDER_STYLES.length} styles</footer>
</body></html>`;

const path = join(out, "preview.html");
writeFileSync(path, html);
console.log(`wrote ${path}`);
